[bayesinteractomics_models]
git-tree-sha1 = "8a1b1654b988cd81ef7ffb60d245f5beee03dd16"
lazy = true

    [[bayesinteractomics_models.download]]
    sha256 = "778e45ec0877d7662625974d8e934b89864f0b9360e24b02f6c17046255bcfc3"
    url = "https://github.com/ma-seefelder/BayesInteractomics.jl/releases/download/models-v1.2.1/models.tar.gz"
